// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using ProductServiceClient.Models;

namespace ProductServiceClient.Models
{
    public static partial class ProductCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Product> DeserializeJson(JToken inputObject)
        {
            IList<Product> deserializedObject = new List<Product>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Product product = new Product();
                product.DeserializeJson(iListValue);
                deserializedObject.Add(product);
            }
            return deserializedObject;
        }
    }
}
